In [5]:
# shows sector performance
# Forex (https://pandas-datareader.readthedocs.io/en/latest/remote_data.html#remote-data-tiingo)
# Alpha Vantage provides sector performances through the top-level function get_sector_performance_av.

import os
import pandas as pd
import pandas_datareader.data as web
from matplotlib import pyplot as plt

In [6]:
web.get_sector_performance_av(api_key = 'EKA9MJ18TLFQY6SJ').head()

,RT,1D,5D,1M,3M,YTD,1Y,3Y,5Y,10Y
Energy,2.62%,2.62%,8.66%,3.40%,21.90%,48.63%,56.57%,33.28%,25.55%,28.43%
Health Care,0.69%,0.69%,2.37%,-6.69%,-0.74%,-8.28%,4.96%,48.40%,72.45%,255.72%
Consumer Staples,0.45%,0.45%,0.70%,-2.29%,2.78%,0.13%,10.70%,36.50%,42.27%,131.04%
Utilities,0.33%,0.33%,-0.23%,-6.16%,8.11%,-0.28%,8.65%,23.44%,38.10%,101.06%
Industrials,-0.17%,-0.17%,-0.38%,-7.16%,-7.59%,-12.29%,-11.28%,24.41%,37.67%,159.36%

In [8]:
# using yahoo finance data
# S&P 500 Industrials (Sector) (^SP500-20)
# S&P 500 Information Technology (Sector) (^SP500-45)
# S&P 500 Health Care (Sector) (^SP500-35)
# S&P 500 Financials (Sector) (^SP500-40)
# S&P 500 Real Estate (Sector) (^SP500-60)
# S&P 500 Energy (Sector) (^GSPE)
# S&P 500 Materials (Sector) (^SP500-15)
# S&P 500 Consumer Discretionary (Sector) (^SP500-25)
# S&P 500 Utilities (Sector) (^SP500-55)
# S&P 500 Consumer Staples (Sector) (^SP500-30)
# S&P 500 Telecommunication Services (Sector) (^SP500-50)

# a dictionary of sector and ticker
sector_dictionary = {
    '^SP500-45' : 'Technology' ,
    '^SP500-20':'Industrials',
    '^SP500-35':'Health Care',
    '^SP500-40':'Financials',
    '^SP500-60':'Real Estate',
    '^GSPE':'Energy',
    '^SP500-15':'Materials',
    '^SP500-25':'Consumer Discretionary',
    '^SP500-55':'Utilities',
    '^SP500-30':'Consumer Staples',
    '^SP500-50':'Telecommunication Services'
    }

sectors = ['^SP500-45','^SP500-20','^SP500-35','^SP500-40','^SP500-60','^GSPE','^SP500-15','^SP500-25','^SP500-55','^SP500-30','^SP500-50']
sector_data = pd.DataFrame()

for a in sectors:
    #you can chagne the start date to any date in 'yyyy-mm-dd' format.
    sector_data[a] = web.DataReader(a, data_source = 'yahoo', start = '2020-1-1')['Adj Close'] 

sector_data.head() #check the beginning of the data

,^SP500-45,^SP500-20,^SP500-35,^SP500-40,^SP500-60,^GSPE,^SP500-15,^SP500-25,^SP500-55,^SP500-30,^SP500-50
Date,,,,,,,,,,,
2020-01-02,1639.119995,700.049988,1190.449951,516.210022,237.139999,460.339996,381.070007,999.010010,323.820007,641.669983,184.029999
2020-01-03,1621.680054,699.229980,1180.329956,510.519989,239.059998,458.769989,374.880005,990.500000,324.179993,640.549988,183.009995
2020-01-06,1626.380005,699.039978,1187.270020,510.230011,239.259995,462.339996,373.190002,994.119995,324.980011,642.070007,185.240005
2020-01-07,1624.589966,698.179993,1184.410034,506.820007,236.399994,461.390015,372.410004,992.869995,324.339996,637.390015,185.169998
2020-01-08,1641.380005,699.780029,1192.030029,509.559998,237.399994,453.359985,374.250000,994.369995,324.329987,640.260010,186.440002

In [9]:
sector_data.tail() #check the end of the data

,^SP500-45,^SP500-20,^SP500-35,^SP500-40,^SP500-60,^GSPE,^SP500-15,^SP500-25,^SP500-55,^SP500-30,^SP500-50
Date,,,,,,,,,,,
2022-05-10,2401.850098,782.849976,1477.689941,558.309998,261.320007,583.659973,510.790009,1173.400024,359.019989,793.969971,196.889999
2022-05-11,2322.639893,775.590027,1468.219971,552.710022,260.890015,591.630005,510.940002,1131.550049,361.779999,791.229980,193.919998
2022-05-12,2296.189941,776.659973,1481.800049,548.799988,262.829987,592.210022,509.980011,1140.550049,357.600006,790.760010,194.910004
2022-05-13,2375.290039,786.260010,1497.400024,556.309998,269.540009,612.250000,517.799988,1187.300049,361.510010,802.000000,199.809998
2022-05-16,2353.699951,784.940002,1507.750000,551.979980,267.380005,628.309998,516.830017,1162.170044,362.690002,805.640015,198.630005